runtime: nodejs10

env_variables:
  SQL_USER: qdlwgooewmhflu
  SQL_PASSWORD: ee8fdfbd8a9104e19451baa259bf78bb8be8f767a50d69e0d5c51e77015e6039
  SQL_DATABASE: d6t60n7r9hfjua
  INSTANCE_CONNECTION_NAME: ec2-3-214-46-194.compute-1.amazonaws.com